****************************************************************************
Design Name: C:/Users/mcarberry/Documents/GitHub/FilterTesting/cadence/Bandpass_Butterworth/pcb/BandPassButterworthTypeI.brd
Rules Checked:  
               component_clearance_audit
               component_orientation_layer_audit
               lead_span_audit
               hole_audit
               test_point_audit

****************************************************************************

ERROR (component_orientation_layer_audit) 
Component           :'C2' 
Orientation         : 270 
Allowed Orientation : 0 
Constraint name     : Default 

ERROR (component_orientation_layer_audit) 
Component           :'L3' 
Orientation         : 90 
Allowed Orientation : 0 
Constraint name     : Default 

***********************************************************************************************
Violations: ERROR = 2    
***********************************************************************************************

Rule Based Summary
***********************************************************************************************
RULENAME                             INFO    OVERSIGHT    WARNING    ERROR    Fatal     TOTAL
component_clearance_audit               0            0          0        0        0         0
component_orientation_layer_audit       0            0          0        2        0         2
lead_span_audit                         0            0          0        0        0         0
hole_audit                              0            0          0        0        0         0
test_point_audit                        0            0          0        0        0         0
TOTAL                                   0            0          0        2        0         2

***********************************************************************************************
